export const Colors = {
  background: 'var(--background)',
  foreground: 'var(--foreground)',
  primary: 'var(--primary)',
  primaryForeground: 'var(--primary-foreground)',
  secondary: 'var(--secondary)',
  secondaryForeground: 'var(--secondary-foreground)',
  muted: 'var(--muted)',
  mutedForeground: 'var(--muted-foreground)',
  accent: 'var(--accent)',
  accentForeground: 'var(--accent-foreground)',
  destructive: 'var(--destructive)',
  destructiveForeground: 'var(--destructive-foreground)',
  ring: 'var(--ring)',
  radius: 'var(--radius)',
  buttonGhost: 'var(--button-ghost)',
  buttonGhostForeground: 'var(--button-ghost-foreground)',
  accent1: 'var(--accent1)',
  accent2: 'var(--accent2)',
  accent3: 'var(--accent3)',
  accent4: 'var(--accent4)',
  accent5: 'var(--accent5)',
  darkGreen: 'var(--dark-green)',
  light: 'var(--light)'
}
